//> using scala "3.2.2"
//> using repository "https://raw.githubusercontent.com/lichess-org/lila-maven/master"
//> using lib "org.lichess::scalachess:14.6.3"
//> using lib "org.typelevel::toolkit::0.0.4"
//> using lib "com.lihaoyi::os-lib:0.9.1"
